# Generated by Django 2.1.2 on 2018-11-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iom', '0006_auto_20181123_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='datafile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
